### ISSUE TITLE
iOS app stuck on importing seed phrase

### ISSUE THREAD

**Issue by v1nsai** [bitpay/bitpay-app#547]
After entering my phrase the app goes back to the home screen where the My Crypto section appears to be loading, but after 10+ minutes it still hasn't loaded.

What I have tried:
* Uninstall/reinstall
* Force closing and restarting the app
* Canceling import and then re-importing
* Entering a wrong seed, which correctly gave me an error, so my seed doesn't seem to be the issue.

Happy to provide any other details, hope this gets fixed soon I'd really like to start using the app!

**Comment by v1nsai** [comment]
I was able to resolve this by tapping "Show Advanced Options" then "Specify Derivation Path" and selecting a currency.  I had a multi-wallet key and just had to import it twice to get both Ethereum and Polygon to show up properly but all works now.

**Comment by NodeX-iHub** [comment]
> I was able to resolve this by tapping "Show Advanced Options" then "Specify Derivation Path" and selecting a currency. I had a multi-wallet key and just had to import it twice to get both Ethereum and Polygon to show up properly but all works now.

Show advanced Option Where
